version: "3.1"
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: 'voltbras'
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  api:
    image: node:alpine
    build: .
    container_name: api
    restart: always
    env_file:
     - .env
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"